version: "3.9"
services:
  postgres:
    image: postgres:15.2-alpine
    container_name: postgres
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - pg_api_data:/var/lib/postgresql/data/
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    container_name: api
    env_file: .env
    depends_on:
      - postgres

  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    container_name: nginx
    ports:
      - 8080:8080
    depends_on:
      - api

volumes:
  pg_api_data:
