version: "3.9"
services:
  postgres:
    image: postgres:15.2-alpine
    container_name: postgres_api
    ports:
      - 5432:5432
    env_file:
      - .env.dev
    volumes:
      - pg_api_data:/var/lib/postgresql/data/
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pg_api_data:
