"""empty message

Revision ID: 4b9588975e80
Revises: f84f13683eed
Create Date: 2023-03-26 20:54:14.688372

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4b9588975e80'
down_revision = 'f84f13683eed'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('moderator_settings', sa.Column('include_reasons', postgresql.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('moderator_settings', 'include_reasons')
    # ### end Alembic commands ###
