"""empty message

Revision ID: 52eb9131568c
Revises: 4b9588975e80
Create Date: 2023-04-02 04:04:13.311514

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '52eb9131568c'
down_revision = '4b9588975e80'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'moderator_settings', 'exclude_servers', existing_type=postgresql.ARRAY(sa.VARCHAR()), nullable=False
    )
    op.alter_column(
        'moderator_settings', 'include_reasons', existing_type=postgresql.ARRAY(sa.VARCHAR()), nullable=False
    )
    op.alter_column(
        'moderator_settings', 'exclude_reasons', existing_type=postgresql.ARRAY(sa.VARCHAR()), nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'moderator_settings', 'exclude_reasons', existing_type=postgresql.ARRAY(sa.VARCHAR()), nullable=True
    )
    op.alter_column(
        'moderator_settings', 'include_reasons', existing_type=postgresql.ARRAY(sa.VARCHAR()), nullable=True
    )
    op.alter_column(
        'moderator_settings', 'exclude_servers', existing_type=postgresql.ARRAY(sa.VARCHAR()), nullable=True
    )
    # ### end Alembic commands ###
