"""empty message

Revision ID: f84f13683eed
Revises: 55e687ca4033
Create Date: 2023-03-20 16:30:05.100049

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'f84f13683eed'
down_revision = '55e687ca4033'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('moderators', sa.Column('is_superuser', sa.Boolean(), nullable=False))
    op.add_column('moderators', sa.Column('is_bot', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('moderators', 'is_bot')
    op.drop_column('moderators', 'is_superuser')
    # ### end Alembic commands ###
