DEFAULT_EXCLUDE_REASONS = [
    'игра с читером',
    'game with cheater',
    'you had eac ban on your account',
    'тим чит',
]
DEFAULT_INCLUDE_REASONS = [
    'macro',
    'макро',
    'eac',
    'еак',
    'm-a',
    'm/a',
    'м/а',
    'multiacc',
    'мультиакк',
    'покинул',
    'отказ',
    'disconnect',
    'вышел',
    'выход',
    'leave',
    'игнор',
    'ignore',
    'результатам',
    'cheat',
    'неверные',
    'чистка',
    'otkaz',
    'liv',
    'чит',
]
